// <auto-generated />
using System;
using APICSHARP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace APICSHARP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191227203554_AlterTableClienteTelefone")]
    partial class AlterTableClienteTelefone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("APICSHARP.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("data_nascimento");

                    b.Property<int?>("Idade")
                        .HasColumnName("idade");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnName("limite_credito");

                    b.Property<string>("Nome")
                        .HasColumnName("nome")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("APICSHARP.Models.ClienteTelefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("ClienteId")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Telefone")
                        .HasColumnName("telefone")
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("cliente_telefone");
                });

            modelBuilder.Entity("APICSHARP.Models.ClienteTelefone", b =>
                {
                    b.HasOne("APICSHARP.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
